image:
  repository: us-central1-docker.pkg.dev/molten-smithy-449113-t6/gke-demo  # Your GCR repository URL
  tag: "13391997312"
  pullPolicy: Always                       # Image pull policy (Always, IfNotPresent, Never)

replicaCount: 1                            # Number of replicas for the deployment
containerPort: 8080                        # Port for the container
