name: Build & Test Maven Project

on:
  push:
    branches:
      - feature/create-bucket    # Trigger on your feature/create-bucket branch
  pull_request:
    branches:
      - feature/create-bucket    # Trigger on pull request to your feature/create-bucket branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install dependencies and run tests
      run: mvn install

    - name: Upload JUnit Test Results
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: junit-reports
        path: target/surefire-reports/**/*.xml

