name: DevSecOps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Maven
        uses: s4u/setup-maven-action@v1.9.0
        with:
          maven-version: '3.8.6'

      - name: Build & Run Tests
        run: mvn clean install

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Docker Authentication for GCR
        run: gcloud auth configure-docker

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/vinay/sprint-boot-app:v1.${{ github.run_number }} .
          docker tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/vinay/sprint-boot-app:v1.${{ github.run_number }} gcr.io/${{ secrets.GCP_PROJECT_ID }}/vinay/sprint-boot-app:latest

      - name: Push Docker Image to GCR
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/vinay/sprint-boot-app:v1.${{ github.run_number }}
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/vinay/sprint-boot-app:latest
