name: Build & Test Maven Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    - name: Set up Maven
      uses: actions/setup-maven@v2
      with:
        maven-version: '3.8.6'

    - name: Build & Run Tests
      run: mvn install

    - name: Upload JUnit Test Results
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: junit-reports
        path: target/surefire-reports/**/*.xml
